In [113]:
import numpy as np

# 1.Write a NumPy program to create a 3X4 array using and iterate over it.


In [114]:
a=np.arange(12).reshape(3,4)

In [115]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [116]:
for i in np.nditer(a):
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

In [117]:
for i in a:      #or
    for j in i:
        print(j,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

# 2.Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.


In [118]:
a=np.linspace(5,50,10)

In [119]:
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


# 3.Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.


In [120]:
a=np.arange(0,21)

In [121]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [122]:
a[(a>=9)&(a<=15)]*=-1

In [123]:
print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


# 4. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.


In [125]:
a=np.random.randint(0,11,5)

In [126]:
print(a)

[ 1  6  5  0 10]


# 5.Write a NumPy program to multiply the values of two given vectors.


In [127]:
a=np.random.randint(0,11,5)
b=np.random.randint(10,21,5)
print(a)
print(b)

[10  1  5  5  7]
[20 10 15 20 19]


In [128]:
c=a*b
print(c)

[200  10  75 100 133]


# 6.Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.


In [129]:
a=np.arange(10,22).reshape(3,4)

In [130]:
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


# 7. Write a NumPy program to find the number of rows and columns of a given matrix.


In [131]:
a=np.arange(10,22).reshape(3,4)

In [132]:
print('No. of rows & columns:',a.shape)

No. of rows & columns: (3, 4)


# 8.Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0.


In [133]:
a=np.eye(3) 
#or a=np.identity(3)

In [134]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 9. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.


In [135]:
a=np.ones((10,10))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [136]:
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 10.Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.


In [137]:
a=np.diag([1,2,3,4,5])

In [138]:
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 11.Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.


In [139]:
a=np.zeros((4,4))

In [140]:
a[::2,1::2]=1
a[1::2,::2]=1

In [141]:
print(a)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


# 12.Write a NumPy program to create a 3x3x3 array filled with arbitrary values.


In [142]:
a=np.random.random((3,3,3))

In [143]:
print(a)

[[[0.35752947 0.48865994 0.57219235]
  [0.30504145 0.21409104 0.29662061]
  [0.72741864 0.35345858 0.03670348]]

 [[0.04294928 0.77676931 0.31830247]
  [0.47126687 0.55448421 0.35714732]
  [0.23008028 0.33076732 0.72731587]]

 [[0.855391   0.89769763 0.30576423]
  [0.32376708 0.20848529 0.30449485]
  [0.25897638 0.63533766 0.71419587]]]


# 13.Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array. 


In [144]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [145]:
print('Sum of all elements:',np.sum(a))
print('Sum of all columns:',np.sum(a,axis=0))
print('Sum of all rows:',np.sum(a,axis=1))

Sum of all elements: 45
Sum of all columns: [12 15 18]
Sum of all rows: [ 6 15 24]


# 14.Write a NumPy program to compute the inner product of two given vectors.


In [146]:
a=np.array([2,3])
b=np.array([4,5])

In [147]:
print(np.dot(a,b))

23


# 15.Write a NumPy program to add a vector to each row of a given matrix.

In [148]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [149]:
b=np.array([1,2,3])
print(b)

[1 2 3]


In [150]:
c=np.empty_like(a)

In [151]:
for i in range(3):
    c[i]=a[i]+b

In [152]:
print(c)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
