In [56]:
import numpy as np

# 1.Write a NumPy program to get the numpy version and show numpy build configuration.

In [57]:
print(np.__version__)

1.18.1


In [58]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Windows 10/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Windows 10/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Windows 10/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windo

# 2.Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.


In [59]:
a=np.array([1,2,3,3.5,4.5,1+0j,2+1j])

In [60]:
print(np.iscomplex(a))

[False False False False False False  True]


In [61]:
print(np.isreal(a))

[ True  True  True  True  True  True False]


In [62]:
print(np.isscalar(4))

True


In [63]:
print(np.isscalar(4.5))

True


In [64]:
print(np.isscalar([4.5]))

False


# 3.Write a NumPy program to test whether none of the elements of a given array is zero.


In [65]:
a=np.array([11,22,33])

In [66]:
print(np.all(a))

True


In [67]:
a=np.array([0,11,22,33])

In [68]:
print(np.all(a))

False


# 4.Write a NumPy program to test whether any of the elements of a given array is non-zero.


In [69]:
a=np.array([0,11,22,33])

In [70]:
print(np.any(a))

True


In [71]:
a=np.array([0,0,0,0])

In [72]:
print(np.any(a))

False


# 5.Write a NumPy program to test element-wise for NaN of a given array.



In [73]:
a=np.array([0,11,22,33])

In [74]:
print(np.isnan(a))

[False False False False]


In [75]:
a=np.array([0,11,22,np.nan])

In [76]:
print(np.isnan(a))

[False False False  True]


# 6.Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.


In [77]:
a=np.array([1,2,3])
b=np.array([0,2,4])

In [78]:
print(np.greater(a,b))
print(np.greater_equal(a,b))
print(np.less(a,b))

[ True False False]
[ True  True False]
[False False  True]


# 7.Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
Input:

x = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100]) 

y = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])


In [79]:
x = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array ([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])

In [80]:
print(np.equal(x,y))

[ True  True  True  True  True  True  True  True  True False]


In [81]:
print(np.allclose(x,y))

True


# 8.Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.


In [82]:
a=np.array([1,7,13,105])

In [83]:
print(a.size*a.itemsize)

16


# 9.Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.


In [84]:
a=np.zeros(10)
b=np.ones(10)
c=np.ones(10)*5

In [85]:
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# 10.Write a NumPy program to create an array of the integers from 30 to 70.


In [89]:
a=np.arange(30,71)

In [90]:
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# 11.Write a NumPy program to create an array of all the even integers from 30 to 70.


In [91]:
a=np.arange(30,71,2)

In [92]:
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# 12.Write a NumPy program to create a 3x3 identity matrix.


In [93]:
a = np.identity(3)

In [94]:
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 13.Write a NumPy program to generate a random number between 0 and 1.


In [95]:
a=np.random.normal(0,1)

In [96]:
print(a)

2.2390424212481483


# 14.Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.


In [97]:
a=np.random.normal(0,1,15)

In [98]:
print(a)

[-0.30233319 -0.48759515 -0.20763685 -0.49240336 -0.17658045 -0.6489839
  0.69732721  1.16006535 -0.86803945  0.59128104 -0.31688342 -0.23647782
  0.92203258 -0.41576966  1.1053034 ]


# 15.Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.


In [99]:
a=np.arange(15,56)

In [100]:
print(a)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [101]:
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
